In [1]:
import random
import numpy as np

In [2]:
def Union(fuzzy_Set_A, fuzzy_Set_B):
    Y = dict()
    for keyA, keyB in zip(fuzzy_Set_A, fuzzy_Set_B): 
        valA = fuzzy_Set_A[keyA] 
        valB = fuzzy_Set_B[keyB] 

        if valA > valB: 
            Y[keyA] = valA 
        else: 
            Y[keyB] = valB 

    print('Union of fuzzy sets A and B is :\n', Y) 

In [3]:
def Intersection(fuzzy_Set_A, fuzzy_Set_B):
    Y = dict()
    for keyA, keyB in zip(fuzzy_Set_A, fuzzy_Set_B): 
        valA = fuzzy_Set_A[keyA] 
        valB = fuzzy_Set_B[keyB] 
        if valA < valB: 
            Y[keyA] = valA 
        else: 
            Y[keyB] = valB 

    print('Intersection of fuzzy sets A and B is :\n', Y) 

In [4]:
def Compliment(fuzzy_Set_A, fuzzy_Set_B):
    Y = dict()
    for keyA in fuzzy_Set_A.keys(): 
        Y[keyA] = round(1 - fuzzy_Set_A[keyA],2) 
    print('Compliment of fuzzy set A is :\n', Y) 

    Y.clear()
    for keyB in fuzzy_Set_B.keys(): 
        Y[keyB] = round(1 - fuzzy_Set_B[keyB],2) 
    print('\n\nCompliment of fuzzy set B is :\n', Y) 

In [5]:
def Difference(fuzzy_Set_A, fuzzy_Set_B):
    Y = dict()
    for keyA, keyB in zip(fuzzy_Set_A, fuzzy_Set_B): 
        valA = fuzzy_Set_A[keyA] 
        valB = fuzzy_Set_B[keyB] 
        valB = round((1 - valB),2)
        if valA < valB: 
            Y[keyA] = valA 
        else: 
            Y[keyB] = valB

    print('Difference of fuzzy sets A and B is :\n', Y) 

    Y.clear()
    for keyA, keyB in zip(fuzzy_Set_A, fuzzy_Set_B): 
        valA = fuzzy_Set_A[keyA] 
        valB = fuzzy_Set_B[keyB] 
        valA = round((1 - valA),2)
        if valB < valA: 
            Y[keyB] = valB 
        else: 
            Y[keyA] = valA

    print('Difference of fuzzy sets B and A is :\n', Y) 

In [6]:
def cartesianProduct(fuzzy_Set_A, fuzzy_Set_B, fuzzy_Set_C):
    AXB = np.zeros((sizeA,sizeB))
    BXC = np.zeros((sizeB,sizeC))
    i=0
    for valA in fuzzy_Set_A.values():
        j = 0
        for valB in fuzzy_Set_B.values():
            if valA < valB:
                AXB[i][j] = valA
            else:
                AXB[i][j] = valB
            j = j + 1
        i = i + 1
    R = AXB
    print('Relation R ( A x B) is : \n', R)

    i = 0
    for valB in fuzzy_Set_B.values():
        j = 0
        for valC in fuzzy_Set_C.values():
            if valB < valC:
                BXC[i][j] = valB
            else:
                BXC[i][j] = valC
            j = j + 1
        i = i + 1
    S = BXC
    print('Relation S ( B x C) is : \n', S)
    return R,S

In [7]:
def max_min_composition(sizeA, sizeB, sizeC, R, S):
    ROS = np.zeros((sizeA,sizeC))
    for i in range(0,sizeA):
        for j in range(0,sizeC):
            element = []
            for k in range(0,sizeB):
                if R[i][k] < S[k][j]:
                    element.append(R[i][k])
                else:
                    element.append(S[k][j])
            #print(element)
            #print()
            ROS[i][j] = max(element)

    print('Max-min composition ROS is :\n', ROS)

In [8]:
fuzzy_Set_A = dict() 
fuzzy_Set_B = dict() 
fuzzy_Set_C = dict() 


while True:
    sizeA = int(input("Enter size of Fuzzy Set A : "))
    sizeB = int(input("Enter size of Fuzzy Set B : "))
    if sizeA != sizeB:
        print("Cant perfom union and intersection of 2 fuzzy sets of different lengths")
        continue
    else:
        break
        
sizeC = int(input("Enter size of Fuzzy Set C : "))

for i in range(sizeA):
    strA = "x"
    strA = strA+str(i)
    fuzzy_Set_A[strA] = round(random.uniform(0,1),2)
    
    strB = "y"
    strB = strB+str(i)
    fuzzy_Set_B[strB] = round(random.uniform(0,1),2)
    
for i in range(sizeC):
    strC = "z"
    strC = strC+str(i)
    fuzzy_Set_C[strC] = round(random.uniform(0,1),2)
fuzzy_Set_A, fuzzy_Set_B, fuzzy_Set_C

Enter size of Fuzzy Set A : 4
Enter size of Fuzzy Set B : 4
Enter size of Fuzzy Set C : 4


({'x0': 0.24, 'x1': 0.4, 'x2': 0.51, 'x3': 0.3},
 {'y0': 1.0, 'y1': 0.04, 'y2': 0.46, 'y3': 0.85},
 {'z0': 0.39, 'z1': 0.39, 'z2': 0.36, 'z3': 0.71})

In [9]:
Union(fuzzy_Set_A, fuzzy_Set_B)

Union of fuzzy sets A and B is :
 {'y0': 1.0, 'x1': 0.4, 'x2': 0.51, 'y3': 0.85}


In [10]:
Intersection(fuzzy_Set_A, fuzzy_Set_B)

Intersection of fuzzy sets A and B is :
 {'x0': 0.24, 'y1': 0.04, 'y2': 0.46, 'x3': 0.3}


In [11]:
Compliment(fuzzy_Set_A, fuzzy_Set_B)

Compliment of fuzzy set A is :
 {'x0': 0.76, 'x1': 0.6, 'x2': 0.49, 'x3': 0.7}


Compliment of fuzzy set B is :
 {'y0': 0.0, 'y1': 0.96, 'y2': 0.54, 'y3': 0.15}


In [12]:
Difference(fuzzy_Set_A, fuzzy_Set_B)

Difference of fuzzy sets A and B is :
 {'y0': 0.0, 'x1': 0.4, 'x2': 0.51, 'y3': 0.15}
Difference of fuzzy sets B and A is :
 {'x0': 0.76, 'y1': 0.04, 'y2': 0.46, 'x3': 0.7}


In [13]:
R,S = cartesianProduct(fuzzy_Set_A, fuzzy_Set_B, fuzzy_Set_C)

Relation R ( A x B) is : 
 [[0.24 0.04 0.24 0.24]
 [0.4  0.04 0.4  0.4 ]
 [0.51 0.04 0.46 0.51]
 [0.3  0.04 0.3  0.3 ]]
Relation S ( B x C) is : 
 [[0.39 0.39 0.36 0.71]
 [0.04 0.04 0.04 0.04]
 [0.39 0.39 0.36 0.46]
 [0.39 0.39 0.36 0.71]]


In [14]:
max_min_composition(sizeA, sizeB, sizeC, R, S)

Max-min composition ROS is :
 [[0.24 0.24 0.24 0.24]
 [0.39 0.39 0.36 0.4 ]
 [0.39 0.39 0.36 0.51]
 [0.3  0.3  0.3  0.3 ]]
